## Numpy ##

In [8]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [13]:
big_list = list(range(100000))
big_array = np.arange(100000)

In [14]:
%timeit [x ** 2 for x in big_list]

11.1 ms ± 406 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
%timeit big_array ** 2

92.2 μs ± 5.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Creating arrays

In [17]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [19]:
b = np.array([[1,2,3,4],[5,6,7,8]]) # 2-D array
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
a = np.array([0,0,0,0])
print(a)

[0 0 0 0]


In [26]:
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
print(np.ones((2,3)))


[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [28]:
print(np.eye(3)) # identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
rng = np.random.default_rng(seed=42)
print(rng.random((2,3)))


[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [31]:
print(rng.integers(1,10,size=(3,3))) # uniform

[[7 7 7]
 [8 5 2]
 [8 5 5]]


In [32]:
print(rng.normal(loc=0, scale = 1, size =5))

[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]


### Array attributes and data types

In [34]:
M = np.array([[1,2,3,],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
print(M.ndim)

2


In [36]:
print(M.shape)

(2, 3)


In [37]:
print(M.size)

6


In [38]:
print(M.dtype)

int64


In [40]:
ints = np.array([1,2,3], dtype=np.int32)
ints.dtype

dtype('int32')

In [41]:
floats = np.array([1,2,3],dtype = np.float64)
floats.dtype

dtype('float64')

### Indexing and Slicing

In [42]:
X = np.arange(10,20)
X

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
print(X[4])

14


In [45]:
print(X[:4])


[10 11 12 13]


In [47]:
M = np.arange(1,13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
print(M[1,2])

7


In [49]:
print(M[0])

[1 2 3 4]


In [50]:
print(M[1])

[5 6 7 8]


In [51]:
print(M[:,0])

[1 5 9]


## Vector operation

In [52]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

In [53]:
print(a)
print(b)

[1 2 3 4]
[10 20 30 40]


In [54]:
print(a+b)

[11 22 33 44]


In [55]:
print(a*b)

[ 10  40  90 160]


In [56]:
# Broadcasting

In [57]:
a = np.array([1,2,3])
b = 10
print(a+b)

[11 12 13]


In [58]:
a = np.array([[1,2,3],
              [4,5,6],])
b = np.array([10,20,30])

In [59]:
print(a+b)

[[11 22 33]
 [14 25 36]]


In [ ]:
a = np.array([1,2,3],
            [4,5,6]])
b = np.array([10,20,30])